import os

WINDOW_HEIGHT = 1080
WINDOW_WIDTH = 1920

HEIGHT = 24
WIDTH = 10

BLOCK_DIMENSIONS = 40
BLOCK_SIZE = (BLOCK_DIMENSIONS, BLOCK_DIMENSIONS)

DEFAULT_SPEED = 550

ROOT_FOLDER = ""
IMG_FOLDER = os.path.join(ROOT_FOLDER, "img")
AUDIO_FOLDER = os.path.join(ROOT_FOLDER, "audio_src")

THEME = os.path.join(AUDIO_FOLDER, "T99Loop.ogg")